# Dockerfile for React client

# Build react client
FROM node:19.9.0-alpine3.16

# Working directory be app
WORKDIR /usr/src/theroutemaster_app

COPY package*.json ./

###  Installing dependencies

RUN npm install --silent

# copy local files to app folder
COPY . .

EXPOSE 3000

CMD ["npm","start"]