# Dockerfile for React client

# Build react client
FROM node:20-alpine

# Working directory be app
WORKDIR /usr/src/theroutemaster_app

COPY package*.json ./

###  Installing dependencies

RUN npm install --silent
RUN npm install --global --silent serve

# copy local files to app folder
COPY . .

RUN npm run build   

EXPOSE 3000

CMD ["npm","start"]