version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: theroutemaster_app-server
    container_name: theroutemaster_app-node-server
    command: npx ts-node server.ts
    volumes:
      - ./server/:/usr/src/theroutemaster_app
      - /usr/src/theroutemaster_app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    networks:
      - theroutemaster-network
    restart: always
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=TheRouteMaster
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - theroutemaster-network
    restart: always
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: theroutemaster_app-client
    container_name: theroutemaster_app-react-client
    command: serve -s build
    volumes:
      - ./client/:/usr/theroutemaster_app
      - /usr/theroutemaster_app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - theroutemaster-network
    restart: always

networks:
    theroutemaster-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local