#  Dockerfile for Node Express Backend

FROM node:20-alpine

# Create App Directory
RUN mkdir -p /usr/src/theroutemaster_app
WORKDIR /usr/src/theroutemaster_app

# Install Dependencies
COPY package*.json ./

RUN npm install --silent

# Copy app source code
COPY . .

# Exports
EXPOSE 5000

CMD ["npm","start"]